CREATE TABLE "users" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL,
    "name" varchar(256) NOT NULL,
    "authLevel" VARCHAR(30) DEFAULT 'USER'
);

CREATE TABLE "styles" (
	"id" SERIAL PRIMARY KEY,
	"style_name" VARCHAR (100) UNIQUE NOT NULL
);

CREATE TABLE "dominant_flavors" (
	"id" SERIAL PRIMARY KEY,
	"flavor_name" VARCHAR (100)
);

CREATE TABLE "breweries" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR (100) NOT NULL,
  "image_url" VARCHAR (1000),
  "image_desc" VARCHAR (256)
);

CREATE TABLE "characteristics" (
	"id" SERIAL PRIMARY KEY,
	"characteristic" VARCHAR (30) UNIQUE NOT NULL
);

CREATE TABLE "beers" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR (80) NOT NULL,
	"style_id" INT REFERENCES "styles",
	"dominant_flavor_id" INT REFERENCES "dominant_flavors",
	"brewery_id" INT REFERENCES "breweries",
  "user_added" boolean DEFAULT true
);

CREATE TABLE "beer_characteristics" (
	"id" SERIAL PRIMARY KEY,
	"beer_id" INT REFERENCES "beers",
	"characteristic_id" INT REFERENCES "characteristics"
);

CREATE TABLE "user_beers" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INT REFERENCES "users",
  "beer_id" INT REFERENCES "beers",
  "is_liked" boolean,
  "has_tried" boolean DEFAULT false
);

INSERT INTO "dominant_flavors" ("flavor_name")
VALUES ('malty'), ('bitter'), ('balanced'), ('hoppy'), ('roasty'), ('sweet'), ('smoke'), ('sour'), ('wood'), ('fruit'), ('spice'), ('juicy');

INSERT INTO "styles" ("style_name")
VALUES ('IPA'), 
('Pilsner'), 
('Hazy IPA'), 
('Sour Ale'), 
('Blonde Ale'),
('Stout'),
('ESB'),
('Smoothie IPA'),
('Pastry Stout'),
('Smoothie Sour'),
('Imperial Stout'),
('Fruited Berliner Weise'),
('Imperial Smoothie Sour'),
('New England DIPA'),
('Lager'),
('Coffee Lager'),
('Fruited Blonde Ale'),
('Amber Lager'),
('Golden Lager'),
('Session IPA'),
('Cream Ale'),
('Summer Ale'),
('Red Ale'),
('Kolsch'),
('Milkshake IPA'),
('Belgian Tripel'),
('Brown Ale'),
('Belgian'),
('Pastry Ale'),
('Porter'),
('Wheat Ale'),
('Imperial Lager'),
('Honey Ale'),
('Ale'),
('Dunkel Lager'),
('Barleywine'),
('Hazy Pale Ale'),
('Table Beer'),
('Saison'),
('Pale Ale');

INSERT INTO "breweries" ("name", "image_url", "image_desc")
VALUES ('Pryes', 'https://lh3.ggpht.com/9mxyCSyWYzSl1YecJaHQ5CyvYtsvEZq3y2k1fJwwVjhudsZbJYS1c0gVWBHm9USAtgs-Et9kqkAU13FF_BQFwQBnp8YwuA=s750', 'Pryes Brewing Logo'), 
  ('Modist', 'https://swag.modistbrewing.com/uploads/b/919d6d60-67bc-11ea-8f20-bfa72d20fbcf/store%20logo.jpg', 'Modist Brewing Logo'), 
  ('Dangerous Man', 'https://i.pinimg.com/originals/99/79/85/99798521204a334461a5f95a52e87198.jpg', 'Dangerous Man Brewing Logo'), 
  ('Indeed', 'https://www.indeedbrewing.com/uploads/press-kit/Indeed_Brewing_Co__Logo_Badge_RGB.png', 'Indeed Brewing Logo'), 
  ('Inbound', 'https://d2pxm94gkd1wuq.cloudfront.net/BreweryLogos/Standard/225213172.pint.glass.black.png', 'Inbound Brew Company Logo'), 
  ('Castle Danger', 'https://www.castledangerbrewery.com/wp-content/uploads/Castle-Danger-Brewery-Full-Color-Logo-e1447365135126.png', 'Castle Danger Brewing Logo'), 
  ('Fulton', 'https://www.mnbeer.com/wp-content/uploads/fulton-brewing-logo-200x200.png', 'Fulton Beer Logo'), 
  ('Fair State', 'https://craftpeak-cooler-images.imgix.net/fair-state-brewing-cooperative/FS-logo-color_2x.png?auto=compress%2Cformat&ixlib=php-1.2.1', 'Fair State Brewing Cooperative Logo');

INSERT INTO "beers" ("name", "style_id", "dominant_flavor_id", "brewery_id", "user_added")
VALUES 
('Miraculum', 1, 4, 1, false),
('Mass Haze-teria', 3, 12, 1, false),
('Royal Rasberry', 4, 8, 1, false),
('Pragmatic Pils', 2, 3, 1, false),
('Course Correct', 39, 12, 1, false),
('Peace Offering', 7, 5, 1, false),
('Bohemian Blonde', 5, 3, 1, false),
('Dublin Dry Stout', 7, 5, 1, false),
('Stoppage Time', 8, 2, 1, false),
('Sunrise Beach', 9, 6, 1, false),
('Outside the Grid', 9, 6, 1, false),
('El Camino', 9, 6, 1, false),
('Northern Tropic', 10, 8, 1, false),
('Blood Orange Miraculum', 1, 4, 1, false),

('The Fix: IWD 2021', 3, 12, 2, false),
('Fish Top Fish Bottom', 11, 5, 2, false), 
('Apiary Drip', 3, 12, 2, false), 
('Half Believing Gravity', 12, 6, 2, false), 
('Fruitropolis', 10, 6, 2, false), 
('Breathing: Conversations', 3, 12, 2, false), 
('Future Pixels', 3, 12, 2, false), 
('Noise Floor', 1, 12, 2, false),
('Bite Size', 7, 5, 2, false), 
('Supra Deluxe', 15, 3, 2, false), 
('False Pattern', 40, 12, 2, false), 
('Dreamyard', 3, 12, 2, false), 
('First Call', 16, 5, 2, false), 

('Sweet Child of Vine', 1, 4, 7, false),
('Lonely Blonde', 5, 3, 3, false),
('Grapefruit Lonely Blonde', 17, 10, 7, false),
('Northern Standard', 18, 1, 7, false),
('Chill City Chugger', 19, 3, 7, false),
('300', 1, 4, 7, false),
('Hopstar', 20, 4, 7, false),

('Castle Cream Ale', 21, 3, 6, false),
('Ode IPA', 1, 4, 6, false),
('17-7 Pale Ale', 40, 4, 6, false),
('North Shore Lager', 18, 1, 6, false),
('George Hunter Stout', 6, 5, 6, false),
('White Pine Project', 1, 4, 6, false),
('Summer Crush', 22, 3, 6, false),
('Mosaic Fresh Hop IPA', 1, 4, 6, false),
('Red Hop', 23, 1, 6, false),

('Contains Bees', 5, 3, 5, false),
('Fruit of the Loop', 1, 12, 5, false),
('Hazy Shades', 3, 12, 5, false),
('Laser Loon', 24, 3, 5, false),
('Rasberry Kolsch', 24, 10, 5, false),
('Stout', 6, 5, 5, false),
('Super G Lovshake', 25, 12, 5, false),
('Rouge Sauvage', 4, 8, 5, false),
('Halucidation', 26, 10, 5, false),
('Coffee Stout', 6, 5, 5, false),
('Rye Whiskey Barrel Aged Cinna-Man Buns', 27, 9, 5, false),

('Belgian Golden Strong', 28, 3, 3, false),
('Better Than... Double Stout', 6, 5, 3, false),
('Boysenberry Frangipane Pastry Ale', 29, 6, 3, false),
('Cherry Twist Stout', 6, 5, 3, false),
('Chocolate Milk Stout', 6, 5, 3, false),
('Cream Ale', 21, 3, 3, false),
('Crewel Juice Imperial Fruited Sour', 4, 8, 3, false),
('Gingersnap Brown Ale', 27, 11, 3, false),
('Hot Ron Double Pale Ale', 40, 4, 3, false),
('House IPA', 1, 4, 3, false),
('Kolsch', 24, 3, 3, false),
('Lemon Guava Danish Pastry Ale', 29, 6, 3, false),
('Nelly Stratado', 3, 4, 3, false),
('Nordic Lodge Ale', 36, 11, 3, false),
('Papaya IPA', 3, 10, 3, false),
('Peanut Butter Porter', 29, 5, 3, false),
('Strawberry Milkshake IPA', 25, 10, 3, false),
('Wee Sexy Lager', 15, 3, 3, false),

('Day Tripper', 40, 4, 4, false),
('Pils', 2, 3, 4, false),
('Lucy', 4, 8, 4, false),
('Mexican Honey Light', 15, 3, 4, false),
('Pistachio Cream Ale', 21, 3, 4, false),
('Zwickel Bier', 2, 3, 4, false),
('Let it Ride', 1, 4, 4, false),
('Flavorwave', 1, 12, 4, false),
('Hop Dab', 1, 4, 4, false),
('Honey Shenanigans', 31, 3, 4, false),
('Stir Crazy', 30, 5, 4, false),
('Oktoberfest', 15, 1, 4, false),
('LSD', 33, 11, 4, false),
('Fresh Hop', 40, 4, 4, false),
('Strawberry Fields', 4, 8, 4, false),
('Bia-Side Pils', 2, 11, 4, false),
('Cerveza de Horchata', 34, 11, 4, false),
('Sarah Janes Maple Sticks', 9, 6, 4, false),
('Pink Rabbit Pils', 2, 3, 4, false),
('Taiga', 1, 10, 4, false),
('Danzig Dunkel', 17, 1, 4, false),
('NE Beer', 27, 3, 4, false),
('Spring Bier', 15, 1, 4, false),

('Air Five', 4, 6, 8, false),
('Big Doinks', 1, 2, 8, false),
('BRAAAAAM', 36, 6, 8, false),
('Dessert Week', 6, 6, 8, false),
('Flavor Pop Technology', 3, 12, 8, false),
('Foamers Lime', 15, 8, 8, false),
('Hey, Remember Pale Ales?', 40, 3, 8, false),
('IPA', 1, 2, 8, false),
('Life Aint Fair', 36, 1, 8, false),
('Main Boss', 9, 6, 8, false),
('Mirror Universe', 3, 12, 8, false),
('Pahlay', 37, 12, 8, false),
('Party Forward', 3, 10, 8, false),
('Petty Cash', 38, 11, 8, false),
('Pils', 2, 2, 8, false),
('Printing Money $$$', 39, 4, 8, false),
('Roselle', 4, 8, 8, false),
('Sastrugi', 3, 10, 8, false),
('Satsuma', 4, 12, 8, false),
('Standard Fun Balls', 36, 1, 8, false),
('Too Far Juice', 4, 6, 8, false),
('Union Lager', 15, 1, 8, false),
('Vienna Lager', 15, 4, 8, false)
;
	
INSERT INTO "characteristics" ("characteristic")
VALUES 
('Citrus'),
('Tart'),
('Juicy'),
('Light'),
('Chocolate'),
('Lemon'),
('Dry'),
('Bitter'),
('Tangerine'),
('Caramel'),
('Hazelnut'),
('Berry'),
('Fruit'),
('Coffee'),
('Hoppy'),
('Wheat'),
('Malty'),
('Balanced'),
('Peanut Butter'),
('Roasted'),
('Orange'),
('Cherry'),
('Cinnamon'),
('Biscuit'),
('Rich'),
('Smooth'),
('Fruity'),
('Crisp'),
('Sweet'),
('Spice'),
('Floral'),
('Bready'),
('Cocoa'),
('Honey'),
('Pine'),
('Dank'),
('Tropical'),
('Ripe'),
('Hazy'),
('Apricot'),
('Brown Sugar'),
('Toffee'),
('Coconut'),
('Rasberry'),
('Vanilla'),
('Black Currant'),
('Pecans'),
('Roasty'),
('Fig'),
('Lavender'),
('Creamy'),
('Thick'),
('Bourban'),
('Guava'),
('Oak'),
('Boozy'),
('Clove'),
('Bright'),
('Dates'),
('Maple'),
('Berries')
;

INSERT INTO "beer_characteristics" ( "beer_id" , "characteristic_id" )
VALUES
	('1', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('1', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('1', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('2', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('2', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Ripe')),
    ('2', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('3', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('3', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hazy')),
    ('3', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('4', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('4', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('4', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('5', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('5', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('5', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('6', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('6', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Berry')),
    ('6', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('7', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Lemon')),
    ('7', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Flroal')),
    ('7', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dry')),
    ('8', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dry')),
    ('8', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasted')),
    ('8', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('9', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bitter')),
    ('9', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Caramel')),
    ('9', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Biscuit')),
    ('10', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tangerine')),
    ('10', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Apricot')),
    ('10', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Guava')),
    ('11', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Caramel')),
    ('11', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Brown Sugar')),
    ('11', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rich')),
    ('12', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hazelnut')),
    ('12', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cocoa')),
    ('12', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rich')),
    ('13', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Berry')),
    ('13', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('13', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('14', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('14', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('14', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Ripe')),
    
    ('15', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('15', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('16', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('16', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Toffee')),
    ('16', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('17', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('17', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Honey')),
    ('17', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('18', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tangerine')),
    ('18', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coconut')),
    ('18', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Vanilla')),
    ('19', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('19', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rasberry')),
    ('19', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('20', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('20', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('21', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('21', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('22', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('22', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('23', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('23', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coconut')),
    ('23', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cocoa Nibs')),
    ('24', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dry')),
    ('24', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('24', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('25', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('25', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('26', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('26', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('27', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('27', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    
    ('28', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('28', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('28', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('29', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Wheat')),
    ('29', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('29', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('30', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('30', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('30', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Wheat')),
    ('31', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('31', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('31', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('32', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dry')),
    ('32', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('32', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('33', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('33', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('34', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Wheat')),
    ('34', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('34', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    
    ('35', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('35', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('35', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('36', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('36', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('36', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('37', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('37', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('37', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Biscuit')),
    ('38', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('38', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Caramel')),
    ('38', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('39', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('39', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('39', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasted')),
    ('40', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('40', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('40', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('41', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Lemon')),
    ('41', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Biscuit')),
    ('41', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('42', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('42', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('42', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('43', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('43', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('43', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    
    ('44', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Peanut Butter')),
    ('44', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('44', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('45', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('45', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('45', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('46', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('46', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('46', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('47', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('47', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('47', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Balanced')),
    ('48', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('48', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('48', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('49', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasted')),
    ('49', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('49', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rich')),
    ('50', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Orange')),
    ('50', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Vanilla')),
    ('50', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('51', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('51', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('51', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Oak')),
    ('52', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cherry')),
    ('52', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Black Currant')),
    ('52', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Boozy')),
    ('53', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasted')),
    ('53', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('53', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('54', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cinnamon')),
    ('54', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pecans')),
    
    ('55', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Biscuit')),
    ('55', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('55', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Clove')),
    ('56', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rich')),
    ('56', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('56', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cocoa')),
    ('57', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('57', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('57', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('58', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('58', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasted')),
    ('58', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('59', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocoalte')),
    ('59', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('59', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('60', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('60', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('60', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('61', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('61', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('61', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('62', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('62', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('62', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Caramel')),
    ('63', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('63', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('63', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('64', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('64', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('64', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('65', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('65', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('65', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('66', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('66', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Lemon')),
    ('66', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('67', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('67', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('67', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('68', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('68', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('68', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('69', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('69', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('69', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('70', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('70', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Roasty')),
    ('70', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Peanut Butter')),
    ('71', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Smooth')),
    ('71', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('71', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bright')),
    ('72', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Light')),
    ('72', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('72', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bright')),
    
    ('73', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('73', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('73', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('74', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('74', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('75', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('75', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('76', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('76', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('76', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Honey')),
    ('77', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('77', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('78', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('78', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('79', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('79', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('79', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('80', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('80', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('81', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('81', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('81', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('82', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('82', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Honey')),
    ('82', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Wheat')),
    ('83', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Cocoa')),
    ('83', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fig')),
    ('83', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coffee')),
    ('84', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('84', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('84', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Rich')),
    -- LSD
    ('85', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Honey')),
    ('85', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Lavender')),
    ('85', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dates')),
    ('86', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('86', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('86', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('87', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('87', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('87', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('88', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('88', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('88', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('89', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('89', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Creamy')),
    ('89', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('90', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('90', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Maple')),
    ('91', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('91', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('91', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('92', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('92', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('92', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('93', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('93', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('93', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('94', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('94', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('94', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coconut')),
    ('95', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('95', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('95', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Ripe')),
    
    ('96', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('96', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Thick')),
    ('96', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Berries')),
    ('97', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dank')),
    ('97', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('97', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bitter')),
    ('98', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('98', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('98', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bourban')),
    ('99', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('99', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('99', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Chocolate')),
    ('100', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('100', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('100', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('101', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('101', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('101', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('102', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('102', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('102', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('103', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Pine')),
    ('103', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bitter')),
    ('103', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('104', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Caramel')),
    ('104', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('104', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Toffee')),
    ('105', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('105', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Thick')),
    ('105', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Coconut')),
    ('106', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('106', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('106', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dank')),
    ('107', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('107', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('107', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('108', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruit')),
    ('108', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('109', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bitter')),
    ('109', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Spice')),
    ('109', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('110', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('110', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bitter')),
    ('111', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('111', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Hoppy')),
    ('111', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Citrus')),
    ('112', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tart')),
    ('112', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Floral')),
    ('112', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('113', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Dank')),
    ('113', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Tropical')),
    ('113', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('114', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Juicy')),
    ('114', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Orange')),
    ('114', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('115', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('115', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bourban')),
    ('115', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Vanilla')),
    ('116', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Sweet')),
    ('116', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Fruity')),
    ('116', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Thick')),
    ('117', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('117', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Bready')),
    ('117', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty')),
    ('118', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Crisp')),
    ('118', (SELECT "id" FROM "characteristics" WHERE "characteristics".characteristic = 'Malty'));